version: "3"

volumes:
  data-vol-db: {}
  minio_storage: {}
  app-sync:
    external: true

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodejs
      - mongodb
      - storage
  mongodb:
    image: mongo:6.0.4
    platform: linux/arm64/v8
    volumes:
      - data-vol-db:/data/db
    ports:
      - "27017:27017"
    container_name: shoopee-mongo-db
  nodejs:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - app-sync:/node/app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/shopeeDB
    command: npm start
    container_name: shopee-app-web
  storage:
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      - "MINIO_ROOT_USER=MINIO_ROOT_USER"
      - "MINIO_ROOT_PASSWORD=MINIO_ROOT_PASSWORD"
    container_name: shopee-storage-cont
    command: server --address ":9000" --console-address ":9001" /data
